# Generated by Django 2.2.3 on 2019-10-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignarImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsignarIntegrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especialidad', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyectos.Categoria')),
                ('imagenes', models.ManyToManyField(through='Proyectos.AsignarImagenes', to='Proyectos.Imagenes')),
                ('integrante', models.ManyToManyField(through='Proyectos.AsignarIntegrante', to='Proyectos.Integrante')),
            ],
        ),
        migrations.AddField(
            model_name='asignarintegrante',
            name='integrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyectos.Integrante'),
        ),
        migrations.AddField(
            model_name='asignarintegrante',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyectos.Proyecto'),
        ),
        migrations.AddField(
            model_name='asignarimagenes',
            name='imagenes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyectos.Imagenes'),
        ),
        migrations.AddField(
            model_name='asignarimagenes',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Proyectos.Proyecto'),
        ),
    ]
